### PR TITLE
Updated validations for polling source and http source + documentation 

### PR DESCRIPTION
**Pull request by shinitiandrei**
**Updated documentation:**
Added a tutorial on how to setup your environment to develop this provider locally. (Feel free to change/improve it)

**Functions added:**
_Resource http source:_
Added TimeZone validation against Sumologic server
_Resource polling source:_
All fields in func resourceSumologicPollingSource() *schema.Resource are being validated against Sumologic Server.
_Update and Delete method working in Polling Source_
_Minor refactorings with naming consistency._

### CODE REVIEW

**Comment by shinitiandrei** [comment]
@josacar Hope that should be enough, thank you for your feedback and patience :)

**Comment by josacar** [comment]
Looks good to me

**Comment by shinitiandrei** [comment]
@erikvanbrakel can you take a look? I think it's all good :)
any changes just ask

**Comment by erikvanbrakel** [comment]
Looks good! Will merge.

**Pull request merged**
