### PR TITLE
Add Cloudsyslog source

### PR DESCRIPTION
**Pull request by josacar**
This change is [Reviewable](https://reviewable.io/reviews/erikvanbrakel/terraform-provider-sumologic/30)

### CODE REVIEW

**Comment by josacar** [comment]
With acceptance tests:

```
$ go test -v ./...
?   	github.com/erikvanbrakel/terraform-provider-sumologic	[no test files]
?   	github.com/erikvanbrakel/terraform-provider-sumologic/go-sumologic	[no test files]
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccSumologicCloudsyslogSource
--- PASS: TestAccSumologicCloudsyslogSource (2.52s)
=== RUN   TestAccSumologicCollector
--- PASS: TestAccSumologicCollector (0.76s)
=== RUN   TestAccSumologicHttpSource
--- PASS: TestAccSumologicHttpSource (1.63s)
=== RUN   TestAccSumologicPollingSource
--- PASS: TestAccSumologicPollingSource (1.28s)
PASS
ok  	github.com/erikvanbrakel/terraform-provider-sumologic/provider	6.272s
```

**Comment by josacar** [comment]
@erikvanbrakel what do you think about supporting Cloud Syslog as it's no longer in Beta?

**Comment by erikvanbrakel** [comment]
Sounds good. At work we're going to use it as well, so it's quite convenient :-)

**Comment by josacar** [comment]
@erikvanbrakel Any showstopper to get this merged?

**Comment by erikvanbrakel** [comment]
Nope. Just got tied up with other things :-)

**Comment by josacar** [comment]
Thanks a lot!

**Pull request merged**
