### PR TITLE
Added more validations for polling source and http source + documentation

### PR DESCRIPTION
**Pull request by shinitiandrei**
Updated documentation:

Added a tutorial on how to setup your environment to develop this provider locally. (Feel free to change or add)
Functions added:

Resource http source:
Added TimeZone validation against Sumologic server
Resource polling source:
All fields in func resourceSumologicPollingSource() *schema.Resource are being validated against Sumologic Server.
File permissions changed
Environment variable changed back to EU
Removed logging
Renamed func to a more consistent one

### CODE REVIEW

**Comment by shinitiandrei** [comment]
It seems that I need to set the keys for Sumologic as you can see in the snippet below: (that's your PR when it passed)
image

In my PR I don't have any of these:
image

Is that right?

**Comment by erikvanbrakel** [comment]
Correct. The problem is that because it's an encrypted value in Travis, it won't inject them when building a 'foreign' PR. If it would, you could submit a malicious PR which would expose it to the world.
If you want to run the tests yourself you should use your own account. I use a free account for that, to isolate it from my company's account.

**Comment by shinitiandrei** [comment]
Yeap, I understand.
I tested on my Travis account with my own Sumologic keys, and everything worked fine as you can see the output below: 
image
image

However, I don't know how to pass in your tests as your keys are protected, of course. Also, I don't want to change your .travis.yml file with my encrypted keys. So, as my code seems all good, how do I proceed? Thanks!

**Comment by josacar** [comment]
There's a lot of noise caused by changing the permissions of a lot of files, could you fix that?

**Comment by erikvanbrakel** [comment]
I'm taking a look at this tomorrow.

**Comment by shinitiandrei** [comment]
@josacar sorry for that man, I've got some issues with file permissions (have to change in order to test). In my perspective, this doesn't affect the code itself but affects the code reviewing indeed. But it's a lot of work now as I need to check file by file and change the permissions...still want me to change?

**Comment by josacar** [comment]
the problem is that affects reviewing and PR is not likely to be merged straight forward as this will be merged in master affecting the following changes.

Maybe we can revert back that commit or even rebase without that commit changing the file permissions.

**Comment by josacar** [comment]
Maybe we can help you with this task, don't worry.

**Comment by shinitiandrei** [comment]
@josacar I understand your point and agree, I will find just the files that I have changed and commit them, bringing back the original file permissions ;)

**Comment by josacar** [comment]
@shinitiandrei Appreciated, reach out if you need anything!

**Comment by josacar** [comment]
@shinitiandrei there's a conflict, could you take a look?

**Comment by shinitiandrei** [comment]
Hi guys, sorry I've been quite busy with my recent project at work and haven't got much time to this PR...I have looked how to reverse my commits or even rebase and in my perspective would take a good part of my time...
The easiest and smooth way for me, if you don't mind, I would close this PR and open a new one with the "real" changes. Is that all good? I can make it by today and tomorrow with your conflict change request as well ;)
Thanks guys!

**Comment by erikvanbrakel** [comment]
That sounds like a simple solution. I like simple ;-)

**Comment by shinitiandrei** [comment]
Would be approximately about 5 to 7 commits with accurate comments about my changes*

**Comment by josacar** [comment]
Great. Thanks in advance.

**Pull request closed without merging**
