### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by josacar**
This change is [Reviewable](https://reviewable.io/reviews/erikvanbrakel/terraform-provider-sumologic/12)

### CODE REVIEW

**Comment by josacar** [comment]
The integration tests are failing in Travis, is it ok?

**Comment by erikvanbrakel** [comment]
That's due to the PR being from outside the main repository. The tests are using API keys which are stored as a secure parameter, and those don't get injected into PRs from foreign repositories. So it's expected, but a bit annoying.

**Comment by erikvanbrakel** [comment]
Can you add a disclaimer to the polling source that the credentials are stored in plain text in the state, which might be a security risk?

**Comment by josacar** [comment]
will do

**Pull request merged**
